---
abstract: 'SCGI Engine'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Engine-SCGI
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.8
  SCGI: 0
resources:
  repository: git://jules.scsys.co.uk/catagits/Catalyst-Engine-SCGI
version: 0.03
